42ity/fty-alert-engine

src/Makemodule-local.am

Problem: waranty rule is not is not created 

---

install.xml
src/fty-alert-engine.conf

Solution: Replace _ with -
Signed-off-by: Tomas Halman <TomasHalman@eaton.com>

Problem: Path with rule is wrong

---

project.xml

No-op in this repo - already on (just removed the flag)

Revive distcheck in Travis

---

install.xml
src/fty_alert_engine.cc

Solution: fix paths again
Signed-off-by: Michal Vyskocil <MichalVyskocil@eaton.com>

Problem: can't get a list of thresholds

---

src/fty_alert_engine.cc
src/templateruleconfigurator.cc
src/templateruleconfigurator.h

Solution: configuration of gpio added

Problem: we want to configure sensor gpio rules 

---

src/templateruleconfigurator.cc

Problem: we need to introduce more parameters into rule template

---

src/fty_alert_engine.cc
src/templateruleconfigurator.cc

Problem: alert-engine cannot configure gpio rule

---

src/templateruleconfigurator.cc
src/templateruleconfigurator.h

Solution: rules are created only for given model

Problem: rules are created even for not relevant gpio sensors

---

src/templateruleconfigurator.cc
src/templateruleconfigurator.h

Problem: iname is still used in rules

---

src/luarule.cc

Problem: alarm messages are not consistent

---

src/fty_alert_engine_server.cc

Adapt to respective change in fty-proto.
Signed-off-by: Michal Marek <MichalMarek1@eaton.com>

Change the action field of alert messages to zlist

---

include/autoconfig.h
src/autoconfig.cc
src/ruleconfigurator.h
src/templateruleconfigurator.cc
src/templateruleconfigurator.h

 Problem: iname is displayed in alarm message instead if ename 

---

src/fty_alert_actions.cc

Solution: added unit test + framework macros

Problem: it's a problem to test functions that are using mlm/zmq communication

---

src/fty_alert_actions.cc

Solution: added support for ACK-* states of alerts

Problem: ACK-* states are ignored by -actions

---

src/fty_alert_actions.cc

Solution: removed doublefree caused by invalid strtok free

Problem: actions agent crash with double free

---

src/fty_alert_actions.cc

Problem: Some tests were commented out.

---

src/autoconfig.cc
src/rule_templates/door-contact.state-change@__device_sensorgpio__.rule
src/rule_templates/pir-motion-detector.state-change@__device_sensorgpio__.rule
src/rule_templates/smoke-detector.state-change@__device_sensorgpio__.rule
src/rule_templates/vibration-sensor.state-change@__device_sensorgpio__.rule
src/rule_templates/water-leak-detector.state-change@__device_sensorgpio__.rule
src/templateruleconfigurator.cc

Solution: Adapt the code and template rules

Problem: Need to support sensorgpio alarm config

---

src/rule_templates/door-contact.state-change@__device_sensorgpio__.rule
src/rule_templates/pir-motion-detector.state-change@__device_sensorgpio__.rule
src/rule_templates/smoke-detector.state-change@__device_sensorgpio__.rule
src/rule_templates/vibration-sensor.state-change@__device_sensorgpio__.rule
src/rule_templates/water-leak-detector.state-change@__device_sensorgpio__.rule
src/templateruleconfigurator.cc

Solution: keep return value in capitals for lua to be able to evaluate the rule

Problem: alert message is (null) for gpi sensors

---

src/fty_alert_actions.cc

Solution: updated timing to proper format and all related to zclock_mono, fixed various debug messages.

Problem: various small bugs in -actions, mostly with generating alert actions periodically (wrong timing format, wrong timing used)

---

include/autoconfig.h
src/autoconfig.cc

(cherry picked from commit 67fdaa9864e36652dc56b66b979411d721c1cdf7)

Fixed alerts not refreshed on asset update

---

src/templateruleconfigurator.cc

Problem: threshold for racks/rows are lost

---

src/templateruleconfigurator.cc

[Do not merge] Problem: threshold for racks/rows are lost

---

src/fty_alert_engine_server.cc

Under higher load, it may happen that we do not empty the pipe fast
enough. This leads to first the agent not responding to mailbox messages
in time and the malamute outgoing queue filling. To avoid this, fetch
all pending metric updates before doing any evaluation and if the same
metric is received more than once, only consider the latest version. We
may miss some spikes and sags in the metrics this way, but we already
miss these by only polling once per 30 seconds.
(cherry picked from commit f72f23ddc9831859d5c1ebdb3bdc7ff57cb474c8)

Discard metrics received too late

---

src/autoconfig.cc
src/fty_alert_actions.cc
src/fty_alert_engine.cc
src/fty_alert_engine_server.cc

Reconciled vs. codebase state in https://github.com/42ity/fty-alert-engine/pull/89

Fix coding style to minimize differences with master branch

---

src/fty_alert_actions.cc
src/fty_alert_engine.cc
src/fty_alert_engine_server.cc

Final touch for today - the only differences of master and release are now in CI recipes to use appropriate dependency branches.

Resync master code - final for 20180125

---

src/fty_alert_actions.cc
src/fty_alert_engine.cc

Final touch for today - the only differences of master and release are now in CI recipes to use appropriate dependency branches.

Resync 1.3 code - final for 20180125

---

src/fty_alert_engine_server.cc

Problem: memcheck failing when building on arm

---

src/rule_templates/load.default@__device_ups__.rule
src/rule_templates/load.input_3phase@__device_epdu__.rule
src/rule_templates/lowbattery@__device_ups__.rule
src/rule_templates/onbattery@__device_ups__.rule
src/rule_templates/onbypass@__device_ups__.rule
src/rule_templates/phase_imbalance@__datacenter__.rule
src/rule_templates/phase_imbalance@__device_epdu__.rule
src/rule_templates/phase_imbalance@__device_ups__.rule
src/rule_templates/phase_imbalance@__rack__.rule
src/rule_templates/realpower.default_1phase@__rack__.rule
src/rule_templates/temperature.default@__device_ups__.rule
src/rule_templates/voltage.input_1phase@__device_ups__.rule
src/rule_templates/voltage.input_3phase@__device_epdu__.rule
src/rule_templates/voltage.input_3phase@__device_ups__.rule
src/templateruleconfigurator.cc

Problem: some alert messages still expose internal ids

---

src/fty_alert_engine.cc

Problem: We need to listen to LICENSING-ANNOUNCEMENTS stream

---

src/rule_templates/load.input_1phase@__device_epdu__.rule
src/rule_templates/load.input_3phase@__device_epdu__.rule

Problem : Automatically ePDU thresholds definition for alarm

---

src/rule_templates/load.input_1phase@__device_epdu__.rule
src/rule_templates/load.input_3phase@__device_epdu__.rule

(cherry picked from commit 35f090ab5553bc04fb02e491159ce5c0276d8bf7)

[Backport to 1.4]Automatically ePDU thresholds definition for alarm

---

src/autoconfig.cc
src/fty_alert_actions.cc

Signed-off-by: barraudl <lilianbarraud@eaton.com>

Handling properly nonactive assets

---

src/fty-alert-engine.service.in
src/fty_alert_engine.cc

Problem: positon of parameters is hard coded

---

src/alertconfiguration.cc
src/fty_alert_actions.cc
src/templateruleconfigurator.cc

Problem: clean agent's log output

---

README.md
src/alertconfiguration.cc
src/alertconfiguration.h
src/autoconfig.cc
src/fty_alert_engine_server.cc
src/rule.cc
src/rule.h

As part of ongoing work, we need the ability to delete rules from the outside.

Add rule deletion API

---

src/rule_templates/sts-frequency@__device_sts__.rule
src/rule_templates/sts-voltage@__device_sts__.rule

Problem flexible alert about ATS/STS is not enough detailed

---

src/rule_templates/door-contact.state-change@__device_sensorgpio__.rule
src/rule_templates/pir-motion-detector.state-change@__device_sensorgpio__.rule
src/rule_templates/smoke-detector.state-change@__device_sensorgpio__.rule
src/rule_templates/vibration-sensor.state-change@__device_sensorgpio__.rule
src/rule_templates/water-leak-detector.state-change@__device_sensorgpio__.rule

Solution: wrapped in JSON and marked by translation macro

Problem: we need to translate alert rule for door contact

---

src/rule_templates/average.humidity@__datacenter__.rule
src/rule_templates/average.humidity@__rack__.rule
src/rule_templates/average.temperature@__datacenter__.rule
src/rule_templates/average.temperature@__rack__.rule
src/rule_templates/load.default@__device_ups__.rule
src/rule_templates/phase_imbalance@__datacenter__.rule
src/rule_templates/phase_imbalance@__rack__.rule
src/rule_templates/realpower.default@__datacenter__.rule

Problem: we need to mark realpower rule strings for translation

---

src/warranty.rule

Problem: we need to mark strings in warranty rule for translation

---

src/rule_templates/licensing.expire@__device_rackcontroller__.rule

Problem: rule for license expiration is missing

---

src/rule_templates/phase_imbalance@__rack__.rule

Problem: missing quotation mark

---

src/rule_templates/voltage.input_1phase@__device_epdu__.rule

Problem: we need to mark alert messages for translation

---

src/fty_alert_engine_server.cc
src/warranty.rule

Solution: warranty alert description now makes more sense and supports thresholds

Problem: warranty alert don't follow thresholds

---

include/autoconfig.h
src/autoconfig.cc

solution : ignore messages about asset already known

prevent overload activity on hourly REPUBLISH

---

src/Makemodule-local.am
src/rule_templates/onacpoweroutage@__device_ups__.rule

This PR is depend to https://github.com/42ity/fty-nut/pull/163

[IPMCVG-2218] add AC power outage new rule

---

src/rule_templates/onacpoweroutage@__device_ups__.rule

[On AC failure] fix bit status

---

src/fty_alert_engine_server.cc

Solution: Replace 'variable' with 'value'.

Problem: Fty-common-translation expects a different key.

---

src/fty_alert_engine_server.cc

Solution: Put them in correctly.

Problem: If conditionals are swapped.

---

src/rule_templates/voltage.input_1phase@__device_epdu__.rule

Add missing TRANSLATE_LUA.

---

src/rule_templates/smoke-detector.state-change@__device_sensorgpio__.rule
src/rule_templates/water-leak-detector.state-change@__device_sensorgpio__.rule

Problem: Smoke and water leak detector are broken

---

src/rule_templates/door-contact.state-change@__device_sensorgpio__.rule

Solution: Fix variable mispelling

Problem: DCS variables is not replaced by its values

---

src/fty_alert_engine_server.cc

Solution: Use correct string for matching.

Problem: Rules contain TRANSLATE_LUA, not TRANSLATE_ME.

---

src/autoconfig.cc
src/rule.cc

Solution: Add Autoconfig UT to validate JSON rules

Problem: We need to catch invalid JSON rules early

---

src/rule_templates/fire-detector-extinguisher.state-change@__device_sensorgpio__.rule
src/rule_templates/fire-detector.state-change@__device_sensorgpio__.rule

Solution: Add the needed rules
Note: this PR completes https://github.com/42ity/fty-sensor-gpio/pull/81

Problem: Need to support Zettler MZXE fire sensor

---

src/header_tests.cc

Solution: Removed TRANSLATE_LUA from UT

Problem: Translation detecting script had issues with UT TRANSLATE_LUA

---

src/fty_alert_config.cc
src/fty_alert_trigger.cc

Solution: changed MB format to send correlation-id first
Do not merge until all related PRs are prepared as well

Problem: inconsitency with fty-alert-list MB messages

---

src/fty_alert_trigger.cc

Solution: flexible should be supported type for LIST MB

Problem: listing flexible rules returns error message

---

src/database.h
src/extended_rules.cc
src/extended_rules.h
src/fty_alert_trigger.cc
src/rule.cc
src/rule.h
src/rule_factory.h

Solution: changed evaluation of rules + fixed pattern rule

Problem: pattern rules are not working

---

src/rule_templates/licensing.expire@__device_rackcontroller__.rule
src/rule_templates/warranty.rule

Signed-off-by: Clement Perrette <clementperrette@eaton.com>

Add again the rules for licence and warranty - need to be rework

---

src/rule_templates/licensing.expire@__device_rackcontroller__.rule
src/rule_templates/warranty.rule

Signed-off-by: Clement Perrette <clementperrette@eaton.com>

Fixed licensing and warranty rules

---

src/fty-alert-engine.cc
src/fty_alert_trigger.cc

Solution: update to proper timeout (units mismatch)
Note to self: don't do direct pushes to master :(

Problem: wrong timeout for trigger based on shm

---

src/fty_alert_config.cc

Solution: fixed __name__ replacement in config

Problem: __name__ replacement don't work properly

---

src/Makemodule-local.am

Solution: added nut template to published files

Problem: missing nut template in production

---

src/Makemodule-local.am

Problem: Templates for Zettler MZX-e are not shipped

---

src/fty-alert-engine.cc
src/fty_alert_actions.cc

Signed-off-by: Clement Perrette <clementperrette@eaton.com>

HOTFIX Add licence limitations

---

src/rule_templates/sts-preferred-source@__device_sts__.rule

Fix
* fix syntax error in sts-preferred-source@__device_sts__.rule

Problem: IPMVAL-1183

---

src/rule_templates/sts-frequency@__device_sts__.rule
src/rule_templates/sts-preferred-source@__device_sts__.rule
src/rule_templates/sts-voltage@__device_sts__.rule

STS alert messages are wrong or malformed.
* fix sts rules templates: TRANSLATE_LUA format

Problem: IPMVAL-1183 (suite)

---

src/alertconfiguration.cc
src/fty_alert_engine_server.cc
src/rule_templates/humidity.default@__device_sensor__.rule
src/rule_templates/temperature.default@__device_sensor__.rule

Solution: do it
- define 'sensor' temperature/humidity rules (threshold)
- avoid automatic instanciation for theses rules (no alert in UI), but let etn-automation instanciate them.

Problem: we need 'automation' rules for sensors - PQSWMBT-3730

---

src/Makemodule-local.am

Solution: complete Makemodule-locale.am

Problem: fire-detector and licensing rules are missing

---

src/rule.cc

Problem: helpless warning for 'automation' action in rule

---

src/rule_templates/licensing.expire@__device_rackcontroller__.rule

Solution: fix it
* fix bool operator syntax error

Problem: licence.expire rule, LUA syntax error

---

src/rule_templates/licensing.expire@__device_rackcontroller__.rule

Problem: licensing.expire rule, bug in LUA evaluation

---

src/rule_templates/door-contact.state-change@__device_sensorgpio__.rule
src/rule_templates/licensing.expire@__device_rackcontroller__.rule
src/rule_templates/sts-frequency@__device_sts__.rule
src/rule_templates/sts-preferred-source@__device_sts__.rule
src/rule_templates/sts-voltage@__device_sts__.rule

FIX
* rm CAT_OTHER for some rules (sts, license)

Problem: IPMVAL-1681, Automation - Trigger on ATS can't be saved

---

src/rule_templates/door-contact.state-change@__device_sensorgpio__.rule
src/rule_templates/licensing.expire@__device_rackcontroller__.rule
src/rule_templates/sts-frequency@__device_sts__.rule
src/rule_templates/sts-preferred-source@__device_sts__.rule
src/rule_templates/sts-voltage@__device_sts__.rule

fix IPMVAL-1681
* rm CAT_OTHER for some rules (sts, license)

Sync release/IPM-2.1.0, fix IPMVAL-1681

---

src/Makemodule-local.am
src/rule_templates/single-point-of-failure@__device_ups__.rule

single-point-of-failure@__device_ups__.rule

Problem: etn-powerchain-analysis needs single-point-of-failure rule

---

src/luarule.cc

log_debug(): in/out and metric values
* more logs

Problem: luarule.cc, lack of logs in evaluate()

---

src/alertconfiguration.cc
src/fty_alert_engine_server.cc
src/purealert.cc
src/purealert.h

IPMVAL-2411-fix

---

include/fty_alert_engine_audit_log.h
project.xml
src/fty-alert-engine-log.cfg
src/fty_alert_engine_audit_log.cc
src/fty_alert_engine_selftest.cc
src/selftest-ro/fty-alert-engine-log-test.cfg

Increase audit log size

---

include/autoconfig.h
src/alertconfiguration.cc
src/autoconfig.cc
src/fty_alert_actions.cc
src/fty_alert_engine_server.cc
src/rule_templates/voltage.input_1phase@__device_epdu__.rule
src/rule_templates/voltage.input_1phase@__device_ups__.rule
src/rule_templates/voltage.input_3phase@__device_epdu__.rule
src/rule_templates/voltage.input_3phase@__device_ups__.rule
src/templateruleconfigurator.cc
src/templateruleconfigurator.h
x-install.sh

PQSWMBT-4916 - Xphase rules exceptions

---

src/rule_templates/voltage.input_1phase@__device_epdu__.rule
src/rule_templates/voltage.input_1phase@__device_ups__.rule
src/rule_templates/voltage.input_3phase@__device_epdu__.rule
src/rule_templates/voltage.input_3phase@__device_ups__.rule

IPMVAL-3118 : fix High thresholds for voltage.input rules
