- packaging/debian/rules
Solution: change lua pc file name before autoreconf and configure
Signed-off-by: Michal Vyskocil <MichalVyskocil@eaton.com>
> Problem: debian packaging can't find Lua

- src/fty-alert-engine.conf
Solution: rename and specify directories
Signed-off-by: Tomas Halman <TomasHalman@eaton.com>
> Problem: configuration file has wrong name and no content

- packaging/debian/fty-alert-engine.install
Reverts 42ity/fty-alert-engine#16
Modified file is generated, problem must be solved in install.xml
> Revert "Problem: Warranty rule is not installed where fty-alert-engine expect…"

- src/luarule.cc
- src/ruleconfigurator.cc
Solution: There is a mixup between macros from <math.h> and templates from <cmath>, so use std::isnan() as recommended In The Net.
> Problem: GNU C++ on some systems has a problem with isnan()

- src/fty_alert_engine.cc
> [ATTENTION: This breaks fty-alert-engine!!!] Problem: New autoconfig actor is not running.

- src/autoconfig.cc
Solution: because alert-engine is off. Use the same path as fty-nut and
other daemons for autoconfig state.
Signed-off-by: Michal Vyskocil <MichalVyskocil@eaton.com>
> Problem: can't get a list of rules

- src/autoconfig.cc
Solution: Since this is autoconfig for alert-engine, use its existing directory.
> Problem: code uses absent /var/lib/fty/fty-autoconfig dir

- src/autoconfig.cc
Error message duplicated
Solution: fty-alert-flexible is known sender now and  error message rephrased
> Problem: error 'unexpected message' generated when reply message from fty-alert-flexible received

- README.md
> Problem: Agent fty-alert-engine lacks README.

- src/fty_alert_actions.cc
Solution: fixed MB reply out of order issue, fixed unit tests
The reason for MB replies was that mlm_client_recv funciton is used to receive MB replies, but this function actually receives anything that was sent to agent, such as other MB messages or even STREAM messages.
> Problem: MB replies come out of order and unit tests are failing

- src/rule_templates/door-contact.state-change@__device_sensorgpio__.rule
- src/rule_templates/pir-motion-detector.state-change@__device_sensorgpio__.rule
- src/rule_templates/smoke-detector.state-change@__device_sensorgpio__.rule
- src/rule_templates/vibration-sensor.state-change@__device_sensorgpio__.rule
- src/rule_templates/water-leak-detector.state-change@__device_sensorgpio__.rule
- src/templateruleconfigurator.cc
Solution: Adapt template and results
Conversely to other flexible managed template rules (such as STS/ATS), GPI have
an "alarm severity" configured at commissioning time, which has to be used when
instanciating rules.
> Problem: Redundant severity / actions for GPI

- include/autoconfig.h
- src/autoconfig.cc
Solution: fixed emplacing with operator[] so that new asset status is reflected in internal structure. Fixed sending updated rule as well.
> Problem: alerts are not refreshed on asset update

- src/fty_alert_actions.cc
Solution: Remove the double free.
> Problem: Agent fty-alert-engine sometines crashes.

- src/fty_alert_engine_server.cc
Under higher load, it may happen that we do not empty the pipe fast
enough. This leads to first the agent not responding to mailbox messages
in time and the malamute outgoing queue filling. To avoid this, fetch
all pending metric updates before doing any evaluation and if the same
metric is received more than once, only consider the latest version. We
may miss some spikes and sags in the metrics this way, but we already
miss these by only polling once per 30 seconds.
> Discard metrics received too late

- include/fty_alert_engine_server.h
- src/autoconfig.cc
- src/fty_alert_actions.cc
- src/fty_alert_engine.cc
- src/fty_alert_engine_server.cc
- src/templateruleconfigurator.cc
Solution: apply back (most of) whitespace markup from the previous codebase state, as it is what zproject generates and what we accept as project coding style
Signed-off-by: Jim Klimov <EvgenyKlimov@eaton.com>
> Problem: too much whitespace change obscures comparison

- src/rule_templates/phase_imbalance@__device_epdu__.rule
- src/rule_templates/phase_imbalance@__device_ups__.rule
The warning and critical thresholds were swapped.
> Fix a typo in UPS and ePDU phase imbalance rule template

- src/templateruleconfigurator.cc
> Problem: blank space between words is removed during rule configuration

- src/fty_alert_engine_server.cc
Signed-off-by: Daviet, Nicolas <NicolasDaviet@eaton.com>
> Problem : missing asset id in rule name for warranty alerts

- src/fty_alert_engine_server.cc
Solution: When mailbox actor gets DELETEALL command and starts deleting rules while the stream actor is evaluating a metric, iterator used by the second actor is invalidated. To avoid this, lock a mutex protecting alertConfiguration structure.
> Problem: Agent fty-alert-engine crashes.

- README.md
- include/autoconfig.h
- include/fty_alert_engine.h
- src/autoconfig.cc
- src/fty_alert_engine_server.cc
- src/templateruleconfigurator.cc
- src/templateruleconfigurator.h
As example :
bmsg request fty-autoconfig rfc-evaluator-rules LIST 12345 "threshold|flexible" 
will returns the list of threshold and flexible templates known in /usr/share/bios/fty-autoconfig
> For automation, we need to publish rule templates

- src/Makemodule-local.am
- src/rule_templates/internal-failure@__device_ups__.rule
Alarm is set to go off on the following alarm bits set:
* fan failure,
* battery charger fail,
* internal UPS fault.
Depends on 42ity/fty-nut#169 to work.
> Add rule internal-failure@__device_ups__.rule

- src/warranty.rule
> (XS/S) Use TRANSLATE_LUA instead of TRANSLATE_ME in a warranty rule.

- src/rule.cc
Problem : 
fty-alert_engine accepts to update a threshold simple rule with a malformed results array.
some result are twiced.
`        "results": [
{
"low_critical": {
"action": [
{
"action": "SMS"
}
],
"severity": "CRITICAL",
"description": "{\"key\" : \"TRANSLATE_LUA(Temperature in rack {{ename}} is critically low.)\", \"variables\" : {\"ename\" : { \"value\" : \"Rack1\", \"assetLink\" : \"rack-6\" } } }",
"threshold_name": "TRANSLATE_LUA(Temperature in rack is critically low)"
},
"low_warning": {
"action": [
{
"action": "SMS"
}
],
"severity": "WARNING",
"description": "{\"key\" : \"TRANSLATE_LUA(Temperature in rack {{ename}} is low.)\", \"variables\" : {\"ename\" : { \"value\" : \"Rack1\", \"assetLink\" : \"rack-6\" } } }", …
> Problem : update simple threshold rule accept malformed results array

- src/rule.cc
(cherry picked from commit 090466b622dd9a0b05adeddcc2b4d191a41f7ce0)
Problem :
fty-alert_engine accepts to update a threshold simple rule with a malformed results array.
some result may twiced.
Solution : ensure that the member count is 1
> [backport 1.5.0] Problem : update simple threshold rule accept bad results array

- src/rule_templates/door-contact.state-change@__device_sensorgpio__.rule
Solution: Fix variable mispelling
(cherry picked from commit 9fa9836132db5ae11a0c17469b96b180ebe2d59c)
> [backport 1.5.0] Problem: DCS variables is not replaced by its values

- src/fty_alert_engine_server.cc
Solution: Use correct string for matching.
(cherry picked from commit c64045a77c01470419a60b4c4fc4bdca06ecbfb1)
Conflicts:
src/fty_alert_engine_server.cc
> Problem: Rules contain TRANSLATE_LUA, not TRANSLATE_ME.

- src/Makemodule-local.am
Solution:
Update Makemodule-local.am, add __device_sensor__ rules in RULE_TEMPLATES
> Problem: sensor rules are missing in /usr/share/bios/fty-autoconfig

- src/rule_templates/internal-failure@__device_ups__.rule
Fix 'variables' token typo on internal-failure@__device_ups__.rule
> Fix internal-failure@__device_ups__.rule

- src/templateruleconfigurator.cc
- src/templateruleconfigurator.h
Instead of ignoring all the alert rules creation in fast track mode, we disable only the realpower
> ignore just total power
